### ISSUE TITLE
HTML

### ISSUE THREAD

**Issue by ColeS82** [ColeS82/Prework-study-guide#1]
# HTML

## User Story
As a bootcamp student
I want the prework notes to be structured on a webpage
so that I can easily find and read information

## Acceptance Criteria
Given a Prework Study Guide website
When I visit the website in my browser
Then I see four boxes titled HTML, CSS, Git, and JavaScript with associated notes listed

**Comment by Ar-Akhil** [comment]
would love to work on it.

**Comment by ColeS82** [comment]
Added HTML code to provide structure to the Pre-work Studyguide.
